name: Rotate Server

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  rotate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Rotate active server
        run: |
          CURRENT=$(cat active.txt)

          if [ "$CURRENT" = "server1" ]; then
            echo "server2" > active.txt
          elif [ "$CURRENT" = "server2" ]; then
            echo "server3" > active.txt
          elif [ "$CURRENT" = "server3" ]; then
            echo "server4" > active.txt
          else
            echo "server1" > active.txt
          fi

      - name: Commit change
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add active.txt
          git commit -m "rotate server"
          git push
